[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
olc_version = "0.8.18"
optimizer_runs = 1_000_000

[fmt]
line_length = 80
number_underscore = "thousands"

[rpc_endpoints]
mainnet = "${MAINNET_RPC_URL}" 
optimism = "${OPTIMISM_RPC_URL}"
goerli = "${GOERLI_RPC_URL}"
optimismGoerli = "${OPTIMISM_GOERLI_RPC_URL}"

[etherscan]
mainnet = { key = "${ETHERSCAN_KEY}" }
optimism = { key = "${ETHERSCAN_KEY}" }
goerli = { key = "${ETHERSCAN_KEY}" }
optimismGoerli = { key = "${ETHERSCAN_KEY}" }