name: test

on: [push]

env:
    FOUNDRY_PROFILE: ci

jobs:
    check:
        strategy:
            fail-fast: true

        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                  submodules: recursive

            - name: Install Foundry
              uses: foundry-rs/foundry-toolchain@v1
              with:
                  version: nightly

            - name: Build Project
              run: |
                  forge --version
                  forge build --sizes
              id: build

            - name: Test Project
              run: |
                forge test --fork-url ${{ secrets.OPTIMISM_GOERLI_RPC_URL }} --etherscan-api-key ${{ secrets.ETHERSCAN_API_KEY }} -vvv
              id: test
    hardhat_test:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
          with:
              submodules: recursive
        - name: Check out repository code
          uses: actions/checkout@v2
        - name: Building on Node.js
          uses: actions/setup-node@v2
          with:
            node-version: '14.17.1'
        - name: Update NPM
          run: npm install -g npm@7.18.1
        - uses: actions/cache@v2
          with:
            path: '**/node_modules'
            key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}
        - name: Install dependencies
          run: npm i --no-audit
        # - name: Compile contracts
        #   run: npx hardhat compile
        - name: Execute contract tests
          run: npx hardhat test
